openapi: 3.1.0
x-stoplight:
  id: dv6haggs43qfb
info:
  title: payment
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/payments:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    students:
                      - id: 1
                        name: Ahmed Mohamed
                      - id: 2
                        name: Sara Ali
                    invoices:
                      - id: 1
                        invoice_number: INV-2024-001
                      - id: 2
                        invoice_number: INV-2024-002
                    payments:
                      - student_id: 1
                        invoice_id: 1
                        amount: 1000
                        payment_date: '2024-01-15'
                        cancelled: false
                properties:
                  students:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                  invoices:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        invoice_number:
                          type: string
                  payments:
                    type: array
                    items:
                      type: object
                      properties:
                        student_id:
                          type: integer
                        invoice_id:
                          type: integer
                        amount:
                          type: number
                        payment_date:
                          type: string
                          format: date
                        cancelled:
                          type: boolean
                        receipt_number:
                          type: string
                          x-stoplight:
                            id: 76w4amv4q2k9l
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
      operationId: get-api-payments
      description: 'Retrieve a list of payments with support for sorting, filtering, pagination, and date range filtering. By default, payments are sorted by payment date in descending order.'
      parameters:
        - schema:
            type: string
          in: query
          name: sort_by
          description: Field to sort by
        - schema:
            type: string
          in: query
          name: sort_direction
          description: Sort direction
        - schema:
            type: string
          in: query
          name: 'q[student_id]'
          description: Filter by student ID
        - schema:
            type: string
          in: query
          name: 'q[invoice_id]'
          description: Filter by invoice ID
        - schema:
            type: string
          in: query
          name: 'q[cancelled]'
          description: Filter by payment status
        - schema:
            type: string
          in: query
          name: 'q[payment_date_from]'
          description: Filter payments from this date
        - schema:
            type: string
          in: query
          name: 'q[payment_date_to]'
          description: Filter payments until this date
        - schema:
            type: string
          in: query
          name: page
          description: Page number for pagination
        - schema:
            type: string
          in: query
          name: per_page
          description: Number of items per page
        - schema:
            type: string
          in: query
          name: 'q[payment_amount]'
  /api/erp/payments:
    post:
      summary: ''
      operationId: post-api-erp-payments
      responses:
        '201':
          description: Created
          content: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    errors:
                      number:
                        - Invalid format
                      total_amount:
                        - Must be positive
                      amount_due:
                        - Must be positive
                      due_date:
                        - Invalid date format
                      status_identifier:
                        - Invalid status
                      currency_code:
                        - Required field
                      updated_at:
                        - System generated field
                      payment_status_identifier:
                        - Invalid payment status
                properties:
                  errors:
                    type: object
                    properties:
                      erp_id:
                        type: array
                        items:
                          type: string
                          x-stoplight:
                            id: o98c2z5orar3e
                      payment_date:
                        type: array
                        items:
                          type: string
                          x-stoplight:
                            id: asqh6sjfuey3q
                      payment_amount:
                        type: array
                        items:
                          type: string
                          x-stoplight:
                            id: vhhjsu6xg1piv
                      receipt_number:
                        type: array
                        items:
                          type: string
                          x-stoplight:
                            id: zqo4pt691cido
                      cancelled:
                        type: array
                        items:
                          type: string
                          x-stoplight:
                            id: zhh1hllx52u45
                      invoice_erp_id:
                        type: array
                        items:
                          type: string
                          x-stoplight:
                            id: c0i0dwqdcrj6b
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  errors:
                    number:
                      - Invalid format
                    total_amount:
                      - Must be positive
                    amount_due:
                      - Must be positive
                    due_date:
                      - Invalid date format
                    status_identifier:
                      - Invalid status
                    currency_code:
                      - Required field
                    updated_at:
                      - System generated field
                    payment_status_identifier:
                      - Invalid payment status
              properties:
                erp_id:
                  type: integer
                  x-stoplight:
                    id: tw9oii2gy6ud1
                payment_date:
                  type: string
                  x-stoplight:
                    id: 83p1n53w1bbqr
                  format: date
                payment_amount:
                  type: number
                  x-stoplight:
                    id: mugr9yd03ns6m
                receipt_number:
                  type: string
                  x-stoplight:
                    id: cjjorxccz2agt
                cancelled:
                  type: boolean
                  x-stoplight:
                    id: ypfgmb0p6gu2w
                invoice_erp_id:
                  type: integer
                  x-stoplight:
                    id: 3anhgf4i4z7ke
              required:
                - erp_id
                - payment_date
                - payment_amount
                - receipt_number
                - invoice_erp_id
          application/xml:
            schema:
              type: object
              properties:
                erp_id:
                  type: integer
                  x-stoplight:
                    id: awyg5cef3q17h
                payment_date:
                  type: string
                  x-stoplight:
                    id: ndsszm02ghxw0
                  format: date
                payment_amount:
                  type: number
                  x-stoplight:
                    id: w5mljz7o29esy
                receipt_number:
                  type: string
                  x-stoplight:
                    id: 9hrprt2w491kq
                cancelled:
                  type: boolean
                  x-stoplight:
                    id: lai0msb9oi8l3
                invoice_erp_id:
                  type: integer
                  x-stoplight:
                    id: 57wrjae4q5rkm
        description: ''
  '/api/erp/payments/{erp_payment_id}':
    patch:
      summary: ''
      operationId: 'patch-api-erp-payments-:erp_payment_id'
      responses:
        '200':
          description: OK
          content: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    errors:
                      number:
                        - Invalid format
                      total_amount:
                        - Must be positive
                      amount_due:
                        - Must be positive
                      due_date:
                        - Invalid date format
                      status_identifier:
                        - Invalid status
                      currency_code:
                        - Required field
                      updated_at:
                        - System generated field
                      payment_status_identifier:
                        - Invalid payment status
                properties:
                  errors:
                    type: object
                    properties:
                      cancelled:
                        type: array
                        items:
                          type: string
                          x-stoplight:
                            id: dpfrsd29319r6
      description: Update payment status (mainly for cancellation/reversal). Used when payment is cancelled or reversed in ERP system.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  cancelled: ''
              properties:
                cancelled:
                  type: boolean
                  x-stoplight:
                    id: 8y49uwtboqqns
    parameters:
      - schema:
          type: string
        name: erp_payment_id
        in: path
        required: true
        description: ERP Payment ID
components:
  schemas: {}
