openapi: 3.1.0
x-stoplight:
  id: gc9k5xuv65mif
info:
  title: weekly_plan
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/api/weekly_plans/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  weekly_plans:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        start_date:
                          type: string
                        end_date:
                          type: string
                        level_id:
                          type: integer
                        will_be_deleted:
                          type: boolean
                        state:
                          type: string
                        weekly_notes:
                          type: 'null'
                        courses_weekly_plan:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              course_groups:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    name:
                                      type: string
                              course:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                  name:
                                    type: string
                              course_group_names:
                                type: string
                              course_groups_weekly_plan:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    course_group_id:
                                      type: integer
                                    weekly_plan_id:
                                      type: integer
                                    created_at:
                                      type: string
                                    updated_at:
                                      type: string
                                    deleted_at:
                                      type: 'null'
                                    courses_weekly_plan_id:
                                      type: integer
                              daily_notes:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    title:
                                      type: string
                                    class_work:
                                      type: string
                                    homework:
                                      type: string
                                    activities:
                                      type: string
                                    date:
                                      type: string
                                    uploaded_files:
                                      type: array
                                      items:
                                        type: object
                                        properties:
                                          id:
                                            type: integer
                                          name:
                                            type: string
                                          original_filename:
                                            type: string
                                          download_name:
                                            type: string
                                          download_url:
                                            type: string
                                          extension:
                                            type: string
                                          upload_type:
                                            type: string
                                          created_at:
                                            type: string
                                          updated_at:
                                            type: string
                        level:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                            section_name:
                              type: string
                            stage_name:
                              type: string
                            level_code:
                              type: string
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      next_page:
                        type: integer
                      prev_page:
                        type: 'null'
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
                x-examples:
                  Example 1:
                    weekly_plans:
                      - id: 27
                        start_date: '2026-07-03'
                        end_date: '2026-08-01'
                        level_id: 1
                        will_be_deleted: false
                        state: unpublished
                        weekly_notes: null
                        courses_weekly_plan:
                          - id: 124
                            course_groups:
                              - id: 6
                                name: A
                              - id: 18
                                name: B
                              - id: 565
                                name: NEWBATCH
                              - id: 581
                                name: final
                            course:
                              id: 78
                              name: Social Studies1(PRKGD)
                            course_group_names: 'A, B, NEWBATCH, final'
                            course_groups_weekly_plan:
                              - id: 271
                                course_group_id: 6
                                weekly_plan_id: 27
                                created_at: '2025-11-05 11:35:44'
                                updated_at: '2025-11-05 11:35:44'
                                deleted_at: null
                                courses_weekly_plan_id: 124
                              - id: 272
                                course_group_id: 18
                                weekly_plan_id: 27
                                created_at: '2025-11-05 11:35:44'
                                updated_at: '2025-11-05 11:35:44'
                                deleted_at: null
                                courses_weekly_plan_id: 124
                              - id: 273
                                course_group_id: 565
                                weekly_plan_id: 27
                                created_at: '2025-11-05 11:35:44'
                                updated_at: '2025-11-05 11:35:44'
                                deleted_at: null
                                courses_weekly_plan_id: 124
                              - id: 274
                                course_group_id: 581
                                weekly_plan_id: 27
                                created_at: '2025-11-05 11:35:44'
                                updated_at: '2025-11-05 11:35:44'
                                deleted_at: null
                                courses_weekly_plan_id: 124
                            daily_notes:
                              - id: 12
                                title: New Subject(PRKGD)
                                class_work: <p>323</p>
                                homework: <p>sas</p>
                                activities: ''
                                date: '2025-11-05'
                                uploaded_files:
                                  - id: 898
                                    name: icon.png
                                    original_filename: icon.png
                                    download_name: icon_png_898.png
                                    download_url: example.com
                                    extension: png
                                    upload_type: device
                                    created_at: '2025-11-05 09:47:53'
                                    updated_at: '2025-11-05 09:47:53'
                        level:
                          id: 1
                          name: PR-KG
                          section_name: American
                          stage_name: Preschool
                          level_code: PRKGD
                    meta:
                      current_page: 1
                      next_page: 2
                      prev_page: null
                      total_pages: 2
                      total_count: 11
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../../Data/UnauthorizedError.yaml
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: ../../Data/ForbiddenError.yaml
      operationId: get-api-weekly_plans-id
      parameters:
        - schema:
            type: integer
          in: query
          name: page
        - schema:
            type: integer
          in: query
          name: per_page
        - schema:
            type: string
          in: query
          name: order_by_start_date
        - schema:
            type: string
          in: query
          name: search_by_level
        - schema:
            type: string
          in: query
          name: search_by_section
        - schema:
            type: string
          in: query
          name: search_by_stage
        - schema:
            type: string
          in: query
          name: search_by_start_date
        - schema:
            type: string
          in: query
          name: search_by_end_date
        - schema:
            type: string
          in: query
          name: search_by_status
  '/api/uploaded_files/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    delete:
      summary: ''
      operationId: delete-api-uploaded_files-id
      responses:
        '204':
          description: No Content
  /api/daily_notes:
    post:
      summary: ''
      operationId: post-api-daily_notes
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  class_work:
                    type: string
                  homework:
                    type: string
                  activities:
                    type: string
                  date:
                    type: string
                  courses_weekly_plan_id:
                    type: integer
                  uploaded_files:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        download_url:
                          type: string
                        extension:
                          type: string
                x-examples:
                  Example 1:
                    id: 25
                    title: Social Studies1(PRKGD)
                    class_work: <p>dvfd</p>
                    homework: ''
                    activities: ''
                    date: '2026-07-05'
                    courses_weekly_plan_id: 124
                    uploaded_files:
                      - id: 1
                        name: worksheet.pdf
                        download_url: 'https://example.com/uploads/worksheet.pdf'
                        extension: pdf
                      - id: 2
                        name: class_image.png
                        download_url: 'https://example.com/uploads/class_image.png'
                        extension: png
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      date:
                        type: array
                        items:
                          type: string
                      weekly_plan_id:
                        type: array
                        items:
                          type: string
                x-examples:
                  Example 1:
                    errors:
                      date:
                        - has already been taken
                      weekly_plan_id:
                        - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                daily_note:
                  type: object
                  properties:
                    courses_weekly_plan_id:
                      type: integer
                    weekly_plan_id:
                      type: integer
                    date:
                      type: string
                    title:
                      type: string
                    class_work:
                      type: string
                    homework:
                      type: string
                    activities:
                      type: string
                    uploaded_files_ids:
                      type: array
                      items:
                        type: integer
              x-examples:
                Example 1:
                  daily_note:
                    courses_weekly_plan_id: 124
                    weekly_plan_id: 27
                    date: '2026-07-05'
                    title: Social Studies1(PRKGD)
                    class_work: <p>dvfd</p>
                    homework: ''
                    activities: ''
                    uploaded_files_ids:
                      - 1
                      - 2
components:
  schemas: {}
