openapi: 3.0.3
x-stoplight:
  id: djbx64p0y5o1e
info:
  title: Social_advisors
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /oauth/token
          scopes:
            public_access: Public access
            erp_access: ERP access
  schemas:
    SocialAdvisor:
      $ref: ../Data/SocialAdvisor.yaml
    Error:
      $ref: ../Data/Error.yaml
security:
  - OAuth2:
      - public_access
paths:
  /social_advisors:
    get:
      summary: Get all social advisors
      tags:
        - SocialAdvisors
      responses:
        '200':
          description: A list of social advisors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SocialAdvisor'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new social advisor
      tags:
        - SocialAdvisors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
      responses:
        '201':
          description: Social advisor created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialAdvisor'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/social_advisors/{id}':
    get:
      summary: Get a social advisor by ID
      tags:
        - SocialAdvisors
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single social advisor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialAdvisor'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
    patch:
      summary: Update a social advisor by ID
      tags:
        - SocialAdvisors
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a social advisor by ID
      tags:
        - SocialAdvisors
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a social advisor by ID
      tags:
        - SocialAdvisors
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
